version: '2'

volumes:
  dbdata_mysql_maria:

services:
  php:
    image: yiisoftware/yii2-php:7.1-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    links:
      - mysql
    depends_on:
      - mysql
    networks:
      - yii2-app-network

  mysql:
    image: mariadb:10.5.2
    container_name: americor-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: americor-test
    volumes:
      - "dbdata_mysql_maria:/var/lib/mysql"
    ports:
      - 127.0.0.1:3503:3306
    networks:
      - yii2-app-network

  nginx:
    image: nginx:latest
    container_name: yii2-nginx
    ports:
      - "80:80"
    volumes:
      - ./web:/var/www/web
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - php
      - mysql
    networks:
      - yii2-app-network

networks:
  yii2-app-network:
    driver: bridge
